version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: PFE
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql

  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - '9001:9000'
      - '9092:9092'
    volumes:
      - 'SonarQube_data:/opt/SonarQube/data'
      - 'SonarQube_extensions:/opt/SonarQube/extensions'
      - 'SonarQube_logs:/opt/SonarQube/logs'

  nexus:
    image: sonatype/nexus3
    ports:
      - '8082:8081'
    volumes:
      - 'nexus_data:/nexus-data'

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8180:8180"
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json

  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - "8889:8888"  # Map Camunda's internal port 8080 to external port 8888

  timemanagement-app:
    depends_on:
      - mysql-db
      - keycloak
      - camunda
    image: ahmedjelassi/timemanagement-app:latest
    restart: on-failure
    ports:
      - '8888:8888'
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql-db:3306/PFE",
        "spring.datasource.username": "admin",
        "spring.datasource.password": "admin",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto": "update",
        "keycloak.realm": "TimeManagement",
        "keycloak.auth-server-url": "http://keycloak:8180",
        "keycloak.ssl-required": "external",
        "keycloak.resource": "timemanagement-back",
        "keycloak.bearer-only": true,
        "keycloak.credentials.secret": "yLp947ZBPCj2ZvjfVxruFmOAWJB1Nqzv",
        "keycloak.use-resource-role-mappings": true,
        "keycloak.principal-attribute": "preferred_username"
      }'

volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus_data:
  mysql-data:
