version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle-db-container
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=XEPDB1
      - ORACLE_PWD=admin
      - ORACLE_PASSWORD=admin
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./oracle-scripts.sql:/docker-entrypoint-initdb.d/init.sql
    command: [ "/bin/sh", "/opt/oracle/scripts/setup/setup.sh" ]

  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - '9001:9000'
      - '9092:9092'
    volumes:
      - 'SonarQube_data:/opt/SonarQube/data'
      - 'SonarQube_extensions:/opt/SonarQube/extensions'
      - 'SonarQube_logs:/opt/SonarQube/logs'
  nexus:
    image: sonatype/nexus3
    ports:
      - '8082:8081'
    volumes:
      - 'nexus_data:/nexus-data'
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8180:8180"
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - "8889:8888"  # Map Camunda's internal port 8080 to external port 8888
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XE
      - SPRING_DATASOURCE_USERNAME=ahmed
      - SPRING_DATASOURCE_PASSWORD=ahmed
      - CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE=true
      - CAMUNDA_BPM_DATABASE_TYPE=oracle
      - CAMUNDA_BPM_HISTORY_LEVEL=full

  timemanagement-app:
    depends_on:
      - oracle-db
      - keycloak
      - camunda
    image: ahmedjelassi/timemanagement-app:latest
    ports:
      - '8888:8888'
    environment:
      SPRING_APPLICATION_JSON:
        '{
            "spring.datasource.url": "jdbc:oracle:thin:@oracle-db:1521/XE",
            "spring.datasource.username": "ahmed",
            "spring.datasource.password": "ahmed",
            "spring.datasource.driver-class-name": "oracle.jdbc.OracleDriver",
            "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.Oracle12cDialect",
            "spring.jpa.hibernate.ddl-auto": "update",
            "keycloak.realm": "TimeManagement",
            "keycloak.auth-server-url": "http://keycloak:8180",
            "keycloak.ssl-required": "external",
            "keycloak.resource": "timemanagement-back",
            "keycloak.bearer-only": true,
            "keycloak.credentials.secret": "yLp947ZBPCj2ZvjfVxruFmOAWJB1Nqzv",
            "keycloak.use-resource-role-mappings": true,
            "keycloak.principal-attribute": "preferred_username",
            "camunda.bpm.schema-update": "true"
          }'

volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus_data:
  dbdata:
  oracle-data: